### PR TITLE
Archive unused repo

### PR DESCRIPTION
**Pull request by ryjones**
There have been no code commits since 2019

Signed-off-by: Ry Jones <ry@linux.com>

### CODE REVIEW

**Comment by hartm** [comment]
I'm fine with archiving this, but I think it should be brought up at a meeting to make sure that no one is using it.  Wrappers by definition don't need to change much, so it's possible someone needs it.

**Review by dcmiddle — APPROVED** [review]
@ryjones are we able to take down the old pypi release too? https://pypi.org/project/python-ursa/

**Comment by mac-arrap** [comment]
While it is true I think that will need a larger review in the Aries and Indy repos. I made this to remove all Indy-Crypto dependencies across indy-node and indy-plenum. Not sure if that was changed later on but it was consumed by those two repos.

**Comment by ryjones** [comment]
> @ryjones are we able to take down the old pypi release too? https://pypi.org/project/python-ursa/

Yes, I can

**Comment by mac-arrap** [comment]
We should also wait until our meeting for us to pull that down. I can confirm by then if this is being used

**Comment by mac-arrap** [comment]
I have confirmed that this a direct dependency of indy-plenum. 

https://github.com/hyperledger/indy-plenum/blob/master/setup.py

**Comment by mac-arrap** [comment]
Closing per above comment

**Pull request closed without merging**
